markdown: rdiscount
highlighter: pygments
permalink: /blog/:title
rdiscount:
  extensions: [smart]

name: Bibhas Debnath
url: https://bibhas.in
description: "Bibhas Debnath, developer from Kolkata, India."
twitter: bibhasdn
github_uname: iambibhas
gravatar_url: https://www.gravatar.com/avatar/ffbd494728961d8baf2c7404dc420152

about_page: /about-me/

comments :
  provider : disqus
  disqus:
    short_name : bee-mblog
  facebook :
    appid : 162354263778470
    num_posts: 5
    width: 580
    colorscheme: light

analytics :
  provider : mixpanel
  mixpanel:
    id: b0dae1534eca0d9521c89110e2ce4081
